"""New registered_column

Revision ID: 9b4ff934d9dc
Revises: 0a6cc7a23000
Create Date: 2024-11-11 19:40:30.989335

"""
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4ff934d9dc'
down_revision = '0a6cc7a23000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_time', sa.DateTime(), nullable=True))

    op.execute(f"UPDATE users SET registered_time = '{datetime.now(timezone.utc)}'")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('registered_time', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('registered_time')

    # ### end Alembic commands ###
