"""Change some of the string length in columns

Revision ID: da0ee097e2c0
Revises: e7c87b5d161f
Create Date: 2024-09-23 17:10:33.429285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0ee097e2c0'
down_revision = 'e7c87b5d161f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.alter_column('text_color',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('common_color',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('background_color',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('blended_color',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.alter_column('blended_color',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.alter_column('background_color',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.alter_column('common_color',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.alter_column('text_color',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)

    # ### end Alembic commands ###
