"""Added new column and relationship in my model logic

Revision ID: e583ce2db802
Revises: f4dac98d4b23
Create Date: 2024-10-19 20:10:04.513013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e583ce2db802'
down_revision = 'f4dac98d4b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'profiles', ['profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###
