"""New bio row in profiles table

Revision ID: 0d659930ba73
Revises: 9b4ff934d9dc
Create Date: 2024-11-22 13:01:40.551378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d659930ba73'
down_revision = '9b4ff934d9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio_description', sa.VARCHAR(length=280), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('bio_description')

    # ### end Alembic commands ###
