"""New bio feature in Group model

Revision ID: 1a5241340dab
Revises: 0d659930ba73
Create Date: 2024-11-23 22:41:08.181456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5241340dab'
down_revision = '0d659930ba73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio_included', sa.BOOLEAN(), nullable=False, server_default=sa.text('FALSE')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.drop_column('bio_included')

    # ### end Alembic commands ###
