"""Delete 2 uel columns as I have them in my links json column:3

Revision ID: 6ab3c204ba24
Revises: da0ee097e2c0
Create Date: 2024-09-23 17:23:14.097309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab3c204ba24'
down_revision = 'da0ee097e2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.drop_column('short_url')
        batch_op.drop_column('original_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('short_url', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
