"""empty message

Revision ID: 7fff91de4fa3
Revises: 6ab3c204ba24
Create Date: 2024-09-25 22:45:26.616414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fff91de4fa3'
down_revision = '6ab3c204ba24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shorten_url', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['shorten_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('shorten_url')

    # ### end Alembic commands ###
