"""New row card color in linksGroup

Revision ID: b33c7180f3aa
Revises: 1a5241340dab
Create Date: 2024-11-25 13:02:09.104472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33c7180f3aa'
down_revision = '1a5241340dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_background_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.drop_column('card_background_color')

    # ### end Alembic commands ###
