"""Some changes in the link table

Revision ID: e7c87b5d161f
Revises: 
Create Date: 2024-09-22 15:28:17.479933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c87b5d161f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.alter_column('links_group_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links_group', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('links_group_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
